version: "3"
services:
  redis:
    image: redis
    ports:
      - "8701:6379"
  mysql:
    image: mysql:5.7
    ports:
      - "8702:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/test-app
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user_testdb
      MYSQL_PASSWORD: password
# Names our volume
  server:
    image: authenticator-service:latest
    ports:
        - "7002:3000"
    environment:
      - APP_DOMAINS
      - AUTHN_URL
      - SECRET_KEY_BASE
      - DATABASE_URL
      - REDIS_URL
    depends_on:
      - redis
      - mysql
volumes:
  db_data: